/-
Import index for the paper-numbered files currently represented in Lean.

Despite the historical filename, these are no longer merely empty placeholders:
many of the files contain completed elementary proofs.  Results whose remaining
content is genuinely hard are routed through named `Aux_...` assumptions so the
numbered file still documents the intended statement.
-/

import DictatorshipTesting.Paper.S03_Lem3_01_DictatorToJunta
import DictatorshipTesting.Paper.S03_Lem3_02_PerfectCompleteness
import DictatorshipTesting.Paper.S04_Lem4_01_CubeSquare
import DictatorshipTesting.Paper.S04_Lem4_04_PMIndependentOfRepresentatives
import DictatorshipTesting.Paper.S04_Lem4_05_PMFixesLocal
import DictatorshipTesting.Paper.S04_Lem4_06_LocalHighDegreeErrorFormula
import DictatorshipTesting.Paper.S04_Lem4_07_PMPerpendicular
import DictatorshipTesting.Paper.S04_Lem4_08_TijLocalDegree
import DictatorshipTesting.Paper.S04_Cor4_09_U1Local
import DictatorshipTesting.Paper.S04_Thm4_10_MatchingGap
import DictatorshipTesting.Paper.S04_Lem4_11_TrialCubeCoordinates
import DictatorshipTesting.Paper.S04_Prop4_12_SquareEnergyControlsGlobalDegree
import DictatorshipTesting.Paper.S04_Lem4_13_OneTrialSoundness
import DictatorshipTesting.Paper.Aux_PMConvolutionLegacy
import DictatorshipTesting.Paper.S05_Lem5_10_OneBoxCornerDecomposition_RowForm
import DictatorshipTesting.Paper.S05_Lem5_10_OneBoxCornerDecomposition_RemovableRow
import DictatorshipTesting.Paper.S05_Lem5_08_SpectralBridgeFromCertificates
import DictatorshipTesting.Paper.S05_Lem5_09_CountingOneMoreMatchingEdge
import DictatorshipTesting.Paper.S05_Lem5_10_ZBoundCertificate
import DictatorshipTesting.Paper.S05_Lem5_12_EvenHCertificate
import DictatorshipTesting.Paper.S05_Lem5_14_OddHCertificate
