/-
Import index for the paper-numbered files currently represented in Lean.

Despite the historical filename, these are no longer merely empty placeholders:
many of the files contain completed elementary proofs.  Results whose remaining
content is genuinely hard are routed through named `Aux_...` assumptions so the
numbered file still documents the intended statement.
-/

import DictatorshipTesting.Paper.S03_Lem3_01_DictatorToJunta
import DictatorshipTesting.Paper.S03_Lem3_02_PerfectCompleteness
import DictatorshipTesting.Paper.S04_Lem4_01_CubeSquare
import DictatorshipTesting.Paper.S04_Lem4_04_PMIndependentOfRepresentatives
import DictatorshipTesting.Paper.S04_Lem4_05_PMFixesLocal
import DictatorshipTesting.Paper.S04_Lem4_06_LocalHighDegreeErrorFormula
import DictatorshipTesting.Paper.S04_Lem4_07_PMPerpendicular
import DictatorshipTesting.Paper.S04_Lem4_08_TijLocalDegree
import DictatorshipTesting.Paper.S04_Cor4_09_U1Local
import DictatorshipTesting.Paper.S04_Thm4_10_MatchingGap
import DictatorshipTesting.Paper.S04_Lem4_11_TrialCubeCoordinates
import DictatorshipTesting.Paper.S04_Prop4_12_SquareEnergyControlsGlobalDegree
import DictatorshipTesting.Paper.S04_Lem4_13_OneTrialSoundness
import DictatorshipTesting.Paper.S05_Def5_01_YoungDiagramsAndBoxes
import DictatorshipTesting.Paper.S05_Def5_02_RemovableCorners
import DictatorshipTesting.Paper.S05_Def5_03_StandardTableaux
import DictatorshipTesting.Paper.S05_Def5_04_TableauCoordinateSpace
import DictatorshipTesting.Paper.S05_Def5_05_ContentAndAdjacentOperators
import DictatorshipTesting.Paper.S05_Lem5_06_AdjacentTranspositionsInYoungsBasis
import DictatorshipTesting.Paper.S05_Lem5_07_DiagonalContentEigenspaces
import DictatorshipTesting.Paper.S05_Def5_08_YoungBlock
import DictatorshipTesting.Paper.S05_Def5_09_TwoBoxRemovals
import DictatorshipTesting.Paper.S05_Def5_10_SignedTwoBoxRemovals
import DictatorshipTesting.Paper.S05_Def5_11_OneBoxRemovals
import DictatorshipTesting.Paper.S05_Lem5_12_TwoBoxTableauBranching
import DictatorshipTesting.Paper.S05_Def5_13_OneBoxDeletionSpaces
import DictatorshipTesting.Paper.S05_Lem5_14_OneBoxCornerDecomposition
import DictatorshipTesting.Paper.S05_Lem5_15_OneBoxDeletionIsUnitary
import DictatorshipTesting.Paper.S05_Lem5_16_OneBoxDeletionIntertwinesEarlierSwaps
import DictatorshipTesting.Paper.S05_Def5_17_EvenSignPatternMultiset
import DictatorshipTesting.Paper.S05_Def5_18_OddSignPatternMultiset
import DictatorshipTesting.Paper.S05_Lem5_19_TwoBoxDimensionRecursion
import DictatorshipTesting.Paper.S05_Lem5_20_OneBoxDimensionRecursion
import DictatorshipTesting.Paper.S05_Lem5_21_SizesOfTheSignPatternMultisets
import DictatorshipTesting.Paper.S05_Def5_22_MatchingCharacters
import DictatorshipTesting.Paper.S05_Lem5_23_MatchingSubgroupEigenbasis
import DictatorshipTesting.Paper.S05_Lem5_24_LocalTruncationOnAMatchingCharacter
import DictatorshipTesting.Paper.S05_Lem5_25_TraceOfOneLocalTruncationOnOneYoungBlock
import DictatorshipTesting.Paper.S05_Def5_26_MatchingIdempotents
import DictatorshipTesting.Paper.S05_Lem5_27_LocalTruncationAsConvolution
import DictatorshipTesting.Paper.S05_Lem5_28_CentralAveragedRejection
import DictatorshipTesting.Paper.S05_Lem5_29_YoungBasisScalarCommutant
import DictatorshipTesting.Paper.S05_Lem5_30_BlockScalarOfTheAveragedRejection
import DictatorshipTesting.Paper.S05_Lem5_31_BlockLowerBoundImpliesTheGap
import DictatorshipTesting.Paper.S05_Lem5_32_EvenSpectralBridge
import DictatorshipTesting.Paper.S05_Lem5_33_OddSpectralBridge
import DictatorshipTesting.Paper.S05_Lem5_34_CountingOneMoreMatchingEdge
import DictatorshipTesting.Paper.S05_Lem5_35_WeightZeroEntriesAreNeverAMajority
import DictatorshipTesting.Paper.S05_Lem5_36_WhereTheInductionCanFail
import DictatorshipTesting.Paper.S05_Lem5_37_EvenCertificate
import DictatorshipTesting.Paper.S05_Lem5_38_OddExceptionalChildren
import DictatorshipTesting.Paper.S05_Lem5_39_OddCertificate

/-
Direct reverse imports (generated):
- `DictatorshipTesting.Paper`
-/

/- Appendix A external representation inputs. -/
import DictatorshipTesting.Paper.AppA_ThmA_01_YoungOrthogonalRealization
import DictatorshipTesting.Paper.AppA_ThmA_02_JucysMurphyContentSpectrum
import DictatorshipTesting.Paper.AppA_ThmA_03_RegularYoungBlockDecomposition
import DictatorshipTesting.Paper.AppA_LemA_04_DegreeOneYoungBlockIdentification
import DictatorshipTesting.Paper.AppA_LemA_05_StandardTableauxSwapConnectedness
