/-
Helper-module import index for paper formalization.

Files imported here are not necessarily paper-numbered.  They include small
cube-Fourier lemmas, matching-cube bookkeeping, averaging identities, and the
explicit external or hard inputs that the numbered paper files depend on.
-/

import DictatorshipTesting.Paper.Aux_CubeFlipInvolutive
import DictatorshipTesting.Paper.Aux_CubeCharFlip
import DictatorshipTesting.Paper.Aux_CubeCharMulSelf
import DictatorshipTesting.Paper.Aux_OrderedMatchingTauDepends
import DictatorshipTesting.Paper.Aux_OrderedMatchingTauMul
import DictatorshipTesting.Paper.Aux_YoungDiagramCorners
import DictatorshipTesting.Paper.Aux_StandardYoungTableaux
import DictatorshipTesting.Paper.Aux_TableauDimension
import DictatorshipTesting.Paper.Aux_YoungAdjacentEntries
import DictatorshipTesting.Paper.Aux_YoungOrthogonal
import DictatorshipTesting.Paper.Aux_YoungAdjacentAction
import DictatorshipTesting.Paper.Aux_YoungMatchingOperators
import DictatorshipTesting.Paper.Aux_CubeCharXor
import DictatorshipTesting.Paper.Aux_CubeHighDegreeLinear
import DictatorshipTesting.Paper.Aux_CubeFourierTranslate
import DictatorshipTesting.Paper.Aux_CubeSquareSpectralFormula
import DictatorshipTesting.Paper.Aux_CubeColorCounting
import DictatorshipTesting.Paper.Aux_CubeLowDegreeError
import DictatorshipTesting.Paper.Aux_MatchingLocalProjection
import DictatorshipTesting.Paper.Aux_PermCubeAverage
import DictatorshipTesting.Paper.Aux_OneTrialDeltaSqExpectationLowerBound
import DictatorshipTesting.Paper.Aux_OneTrialRejectProbabilityLowerBound
import DictatorshipTesting.Paper.Aux_SpectralBridgeRepresentationInputs
import DictatorshipTesting.Paper.Aux_SpectralBridgeFromCertificates
import DictatorshipTesting.Paper.Aux_SpectralBridgeDimensionParam
import DictatorshipTesting.Paper.S02_Thm2_01_BooleanU1Classification
import DictatorshipTesting.Paper.S02_Thm2_02_FKNStability
import DictatorshipTesting.Paper.S05_Def5_01_YoungDiagramsAndBoxes
import DictatorshipTesting.Paper.S05_Def5_02_RemovableCorners
import DictatorshipTesting.Paper.S05_Def5_03_StandardTableaux
import DictatorshipTesting.Paper.S05_Def5_04_TableauCoordinateSpace
import DictatorshipTesting.Paper.S05_Def5_05_ContentAndAdjacentOperators
import DictatorshipTesting.Paper.S05_Lem5_06_AdjacentTranspositionsInYoungsBasis
import DictatorshipTesting.Paper.S05_Lem5_07_DiagonalContentEigenspaces
import DictatorshipTesting.Paper.S05_Def5_08_YoungBlock
import DictatorshipTesting.Paper.S05_Def5_09_TwoBoxRemovals
import DictatorshipTesting.Paper.S05_Def5_10_SignedTwoBoxRemovals
import DictatorshipTesting.Paper.S05_Def5_11_OneBoxRemovals
import DictatorshipTesting.Paper.S05_Lem5_12_TwoBoxTableauBranching
import DictatorshipTesting.Paper.S05_Def5_13_OneBoxDeletionSpaces
import DictatorshipTesting.Paper.S05_Lem5_14_OneBoxCornerDecomposition
import DictatorshipTesting.Paper.S05_Lem5_15_OneBoxDeletionIsUnitary
import DictatorshipTesting.Paper.S05_Lem5_16_OneBoxDeletionIntertwinesEarlierSwaps
import DictatorshipTesting.Paper.S05_Def5_17_EvenSignPatternMultiset
import DictatorshipTesting.Paper.S05_Def5_18_OddSignPatternMultiset
import DictatorshipTesting.Paper.S05_Lem5_19_TwoBoxDimensionRecursion
import DictatorshipTesting.Paper.S05_Lem5_20_OneBoxDimensionRecursion
import DictatorshipTesting.Paper.S05_Lem5_21_SizesOfTheSignPatternMultisets
import DictatorshipTesting.Paper.S05_Def5_22_MatchingCharacters
import DictatorshipTesting.Paper.S05_Lem5_23_MatchingSubgroupEigenbasis
import DictatorshipTesting.Paper.S05_Lem5_24_LocalTruncationOnAMatchingCharacter
import DictatorshipTesting.Paper.S05_Lem5_25_TraceOfOneLocalTruncationOnOneYoungBlock
import DictatorshipTesting.Paper.S05_Def5_26_MatchingIdempotents
import DictatorshipTesting.Paper.S05_Lem5_27_LocalTruncationAsConvolution
import DictatorshipTesting.Paper.S05_Lem5_28_CentralAveragedRejection
import DictatorshipTesting.Paper.S05_Lem5_29_YoungBasisScalarCommutant
import DictatorshipTesting.Paper.S05_Lem5_30_BlockScalarOfTheAveragedRejection
import DictatorshipTesting.Paper.S05_Lem5_31_BlockLowerBoundImpliesTheGap
import DictatorshipTesting.Paper.S05_Lem5_32_EvenSpectralBridge
import DictatorshipTesting.Paper.S05_Lem5_33_OddSpectralBridge
import DictatorshipTesting.Paper.S05_Lem5_34_CountingOneMoreMatchingEdge
import DictatorshipTesting.Paper.S05_Lem5_35_WeightZeroEntriesAreNeverAMajority
import DictatorshipTesting.Paper.S05_Lem5_36_WhereTheInductionCanFail
import DictatorshipTesting.Paper.S05_Lem5_37_EvenCertificate
import DictatorshipTesting.Paper.S05_Lem5_38_OddExceptionalChildren
import DictatorshipTesting.Paper.S05_Lem5_39_OddCertificate

/- Appendix A external representation inputs. -/
import DictatorshipTesting.Paper.AppA_ThmA_01_YoungOrthogonalRealization
import DictatorshipTesting.Paper.AppA_ThmA_02_JucysMurphyContentSpectrum
import DictatorshipTesting.Paper.AppA_ThmA_03_RegularYoungBlockDecomposition
import DictatorshipTesting.Paper.AppA_LemA_04_DegreeOneYoungBlockIdentification
import DictatorshipTesting.Paper.AppA_LemA_05_StandardTableauxSwapConnectedness
