/-
Import index for the paper-numbered files currently represented in Lean.

Despite the historical filename, these are no longer merely empty placeholders:
many of the files contain completed elementary proofs.  Results whose remaining
content is genuinely hard are routed through named `Aux_...` assumptions so the
numbered file still documents the intended statement.
-/

import DictatorshipTesting.Paper.S03_Lem3_01_DictatorToJunta
import DictatorshipTesting.Paper.S03_Lem3_02_PerfectCompleteness
import DictatorshipTesting.Paper.S04_Lem4_01_CubeSquare
import DictatorshipTesting.Paper.S04_Lem4_04_PMIndependentOfRepresentatives
import DictatorshipTesting.Paper.S04_Lem4_05_PMFixesLocal
import DictatorshipTesting.Paper.S04_Lem4_06_LocalHighDegreeErrorFormula
import DictatorshipTesting.Paper.S04_Lem4_07_PMPerpendicular
import DictatorshipTesting.Paper.S04_Lem4_08_TijLocalDegree
import DictatorshipTesting.Paper.S04_Cor4_09_U1Local
import DictatorshipTesting.Paper.S04_Thm4_10_MatchingGap
import DictatorshipTesting.Paper.S04_Lem4_11_TrialCubeCoordinates
import DictatorshipTesting.Paper.S04_Prop4_12_SquareEnergyControlsGlobalDegree
import DictatorshipTesting.Paper.S04_Lem4_13_OneTrialSoundness
import DictatorshipTesting.Paper.S05_Lem5_01_AdjacentTranspositionsInYoungsBasis
import DictatorshipTesting.Paper.S05_Lem5_02_DiagonalContentEigenspaces
import DictatorshipTesting.Paper.S05_Def5_03_YoungBlock
import DictatorshipTesting.Paper.S05_Def5_04_TwoBoxRemovals
import DictatorshipTesting.Paper.S05_Def5_05_SignedTwoBoxRemovals
import DictatorshipTesting.Paper.S05_Def5_06_OneBoxRemovals
import DictatorshipTesting.Paper.S05_Lem5_07_TwoBoxTableauBranching
import DictatorshipTesting.Paper.S05_Def5_08_OneBoxDeletionSpaces
import DictatorshipTesting.Paper.S05_Lem5_09_OneBoxCornerDecomposition
import DictatorshipTesting.Paper.S05_Lem5_10_OneBoxDeletionIsUnitary
import DictatorshipTesting.Paper.S05_Lem5_11_OneBoxDeletionIntertwinesEarlierSwaps
import DictatorshipTesting.Paper.S05_Def5_12_EvenSignPatternMultiset
import DictatorshipTesting.Paper.S05_Def5_13_OddSignPatternMultiset
import DictatorshipTesting.Paper.S05_Lem5_14_TwoBoxDimensionRecursion
import DictatorshipTesting.Paper.S05_Lem5_15_OneBoxDimensionRecursion
import DictatorshipTesting.Paper.S05_Lem5_16_SizesOfTheSignPatternMultisets
import DictatorshipTesting.Paper.S05_Def5_17_MatchingCharacters
import DictatorshipTesting.Paper.S05_Lem5_18_MatchingSubgroupEigenbasis
import DictatorshipTesting.Paper.S05_Lem5_19_LocalTruncationOnAMatchingCharacter
import DictatorshipTesting.Paper.S05_Lem5_20_TraceOfOneLocalTruncationOnOneYoungBlock
import DictatorshipTesting.Paper.S05_Def5_21_MatchingIdempotents
import DictatorshipTesting.Paper.S05_Lem5_22_LocalTruncationAsConvolution
import DictatorshipTesting.Paper.S05_Lem5_23_CentralAveragedRejection
import DictatorshipTesting.Paper.S05_Lem5_24_YoungBasisScalarCommutant
import DictatorshipTesting.Paper.S05_Lem5_25_BlockScalarOfTheAveragedRejection
import DictatorshipTesting.Paper.S05_Lem5_26_BlockLowerBoundImpliesTheGap
import DictatorshipTesting.Paper.S05_Lem5_27_EvenSpectralBridge
import DictatorshipTesting.Paper.S05_Lem5_28_OddSpectralBridge
import DictatorshipTesting.Paper.S05_Lem5_29_CountingOneMoreMatchingEdge
import DictatorshipTesting.Paper.S05_Lem5_30_WeightZeroEntriesAreNeverAMajority
import DictatorshipTesting.Paper.S05_Lem5_31_WhereTheInductionCanFail
import DictatorshipTesting.Paper.S05_Lem5_32_EvenCertificate
import DictatorshipTesting.Paper.S05_Lem5_33_OddExceptionalChildren
import DictatorshipTesting.Paper.S05_Lem5_34_OddCertificate

/- Appendix A external representation inputs. -/
import DictatorshipTesting.Paper.AppA_ThmA_01_YoungOrthogonalRealization
import DictatorshipTesting.Paper.AppA_ThmA_02_JucysMurphyContentSpectrum
import DictatorshipTesting.Paper.AppA_ThmA_03_RegularYoungBlockDecomposition
import DictatorshipTesting.Paper.AppA_LemA_04_DegreeOneYoungBlockIdentification
import DictatorshipTesting.Paper.AppA_LemA_05_StandardTableauxSwapConnectedness
