import DictatorshipTesting.Paper.Defs.S03_Def3_03_OrderedMatchingEdgePerm
/-
Direct reverse imports:
- `DictatorshipTesting.Paper.Defs.S03_Def3_05_MatchingCubeRestriction`
- `DictatorshipTesting.Paper.S03_Int_OrderedMatchingTauDepends`
-/


/-!
Definition file for `OrderedMatching.tau`.
-/

noncomputable section

open scoped BigOperators

namespace DictatorshipTesting

/-- The cube element `tau_x` generated by the matching transpositions. -/
def OrderedMatching.tau {α : Type*} [DecidableEq α]
    (M : OrderedMatching α) (x : Cube M.edgeCount) : Perm α :=
  (List.ofFn fun r : Fin M.edgeCount => M.edgePerm x r).prod

end DictatorshipTesting
