/-
Root import file for the `DictatorshipTesting` Lean library.

The project is split into small files so individual paper lemmas can be opened
and worked on directly.  This root file imports the represented paper statements
directly rather than routing through extra wrapper indexes.
-/

import DictatorshipTesting.Basic
import DictatorshipTesting.BasicFacts
import DictatorshipTesting.SetFacts
import DictatorshipTesting.SetFacts.Fact_sub_sd_SetMinusSymmDiff
import DictatorshipTesting.AlgebraicProperty


/- Paper-numbered files currently represented in Lean. -/
import DictatorshipTesting.Paper.S01_Thm1_01_MainIntro
import DictatorshipTesting.Paper.S02_Thm2_01_BooleanU1Classification
import DictatorshipTesting.Paper.S02_Thm2_02_FKNStability
import DictatorshipTesting.Paper.S02_Lem2_03_CubeCharOrthonormality
import DictatorshipTesting.Paper.S02_Lem2_03_CubeFourierExpansion
import DictatorshipTesting.Paper.S02_Lem2_03_CubeParsevalIdentity
import DictatorshipTesting.Paper.S02_Lem2_03_CubeParseval
import DictatorshipTesting.Paper.S03_Lem3_01_DictatorToJunta
import DictatorshipTesting.Paper.S03_Lem3_02_PerfectCompleteness
import DictatorshipTesting.Paper.S04_Lem4_01_CubeSquare
import DictatorshipTesting.Paper.S04_Lem4_02_PMIndependentOfRepresentatives
import DictatorshipTesting.Paper.S04_Lem4_03_PMFixesLocal
import DictatorshipTesting.Paper.S04_Lem4_04_LocalHighDegreeErrorFormula
import DictatorshipTesting.Paper.S04_Lem4_05_PMPerpendicular
import DictatorshipTesting.Paper.S04_Lem4_06_TijLocalDegree
import DictatorshipTesting.Paper.S04_Cor4_07_U1Local
import DictatorshipTesting.Paper.S04_Thm4_08_MatchingGap
import DictatorshipTesting.Paper.S04_Lem4_09_TrialCubeCoordinates
import DictatorshipTesting.Paper.S04_Prop4_10_SquareEnergyControlsGlobalDegree
import DictatorshipTesting.Paper.S04_Lem4_11_OneTrialSoundness
import DictatorshipTesting.Paper.Defs.S05_Def5_01_YoungDiagramsAndBoxes
import DictatorshipTesting.Paper.Defs.S05_Def5_02_RemovableCorners
import DictatorshipTesting.Paper.Defs.S05_Def5_03_StandardTableaux
import DictatorshipTesting.Paper.Defs.S05_Def5_04_TableauCoordinateSpace
import DictatorshipTesting.Paper.Defs.S05_Def5_05_ContentAndAdjacentOperators
import DictatorshipTesting.Paper.S05_Lem5_01_AdjacentTranspositionsInYoungsBasis
import DictatorshipTesting.Paper.S05_Lem5_02_DiagonalContentEigenspaces
import DictatorshipTesting.Paper.S05_Lem5_03_ConnectednessOfStandardTableaux
import DictatorshipTesting.Paper.Defs.S05_Def5_06_YoungBlock
import DictatorshipTesting.Paper.Defs.S05_Def5_07_YoungBlockEnergyProfile
import DictatorshipTesting.Paper.Defs.S05_Def5_08_U1CompatibleYoungBlockProfile
import DictatorshipTesting.Paper.Defs.S05_Def5_09_TwoBoxRemovals
import DictatorshipTesting.Paper.Defs.S05_Def5_10_SignedTwoBoxRemovals
import DictatorshipTesting.Paper.Defs.S05_Def5_11_OneBoxRemovals
import DictatorshipTesting.Paper.S05_Lem5_04_TwoBoxTableauBranching
import DictatorshipTesting.Paper.Defs.S05_Def5_12_OneBoxDeletionSpaces
import DictatorshipTesting.Paper.S05_Lem5_05_OneBoxCornerDecomposition
import DictatorshipTesting.Paper.S05_Lem5_06_OneBoxDeletionIsUnitary
import DictatorshipTesting.Paper.S05_Lem5_07_OneBoxDeletionIntertwinesEarlierSwaps
import DictatorshipTesting.Paper.Defs.S05_Def5_13_EvenSignPatternMultiset
import DictatorshipTesting.Paper.Defs.S05_Def5_14_OddSignPatternMultiset
import DictatorshipTesting.Paper.S05_Lem5_08_TwoBoxDimensionRecursion
import DictatorshipTesting.Paper.S05_Lem5_09_OneBoxDimensionRecursion
import DictatorshipTesting.Paper.S05_Lem5_10_SizesOfTheSignPatternMultisets
import DictatorshipTesting.Paper.Defs.S05_Def5_15_MatchingCharacters
import DictatorshipTesting.Paper.Defs.S05_Def5_16_IsMatchingEigenvectorEven
import DictatorshipTesting.Paper.Defs.S05_Def5_17_IsMatchingEigenvectorOdd
import DictatorshipTesting.Paper.Defs.S05_Def5_18_MatchingRestrictionEvenInput
import DictatorshipTesting.Paper.Defs.S05_Def5_19_MatchingRestrictionOddInput
import DictatorshipTesting.Paper.S05_Lem5_11_MatchingSubgroupEigenbasis
import DictatorshipTesting.Paper.S05_Lem5_12_LocalTruncationOnAMatchingCharacter
import DictatorshipTesting.Paper.Defs.S05_Def5_20_TraceLocalTruncationEvenInput
import DictatorshipTesting.Paper.Defs.S05_Def5_21_TraceLocalTruncationOddInput
import DictatorshipTesting.Paper.S05_Lem5_13_TraceOfOneLocalTruncationOnOneYoungBlock
import DictatorshipTesting.Paper.Defs.S05_Def5_22_MatchingIdempotents
import DictatorshipTesting.Paper.S05_Lem5_14_LocalTruncationAsConvolution
import DictatorshipTesting.Paper.S05_Lem5_15_CentralAveragedRejection
import DictatorshipTesting.Paper.Defs.S05_Def5_23_YoungBasisScalarCommutantInput
import DictatorshipTesting.Paper.S05_Lem5_16_YoungBasisScalarCommutant
import DictatorshipTesting.Paper.S05_Lem5_17_BlockScalarOfTheAveragedRejection
import DictatorshipTesting.Paper.S05_Lem5_17a_AveragedRejectionYoungOperator
import DictatorshipTesting.Paper.Defs.S05_Def5_28_GroupAlgebraAction
import DictatorshipTesting.Paper.Defs.S05_Def5_29_AveragedHighMatchingElement
import DictatorshipTesting.Paper.Defs.S05_Def5_30_TableauOperatorTrace
import DictatorshipTesting.Paper.S05_Lem5_18_BlockLowerBoundImpliesTheGap
import DictatorshipTesting.Paper.S05_Lem5_19_RegularYoungBlockDecomposition
import DictatorshipTesting.Paper.S05_Lem5_20_EvenSpectralBridge
import DictatorshipTesting.Paper.S05_Lem5_21_OddSpectralBridge
import DictatorshipTesting.Paper.S05_Lem5_22_CountingOneMoreMatchingEdge
import DictatorshipTesting.Paper.S05_Lem5_23_WeightZeroEntriesAreNeverAMajority
import DictatorshipTesting.Paper.S05_Lem5_24_WhereTheInductionCanFail
import DictatorshipTesting.Paper.S05_Lem5_25_EvenCertificate
import DictatorshipTesting.Paper.S05_Lem5_26_OddExceptionalChildren
import DictatorshipTesting.Paper.S05_Lem5_27_OddCertificate
import DictatorshipTesting.Paper.Defs.AppA_DefA_01_YoungOrthogonalActionData
import DictatorshipTesting.Paper.Defs.AppA_DefA_02_JucysMurphyContentActionData
import DictatorshipTesting.Paper.AppA_ThmA_01_YoungOrthogonalRealization
import DictatorshipTesting.Paper.AppA_ThmA_02_JucysMurphyContentSpectrum
import DictatorshipTesting.Paper.AppA_LemA_03_DegreeOneYoungBlockIdentification

/-
Direct reverse imports:
- none
-/
