/-
Root import file for the `DictatorshipTesting` Lean library.

The project is split into small files so individual paper lemmas can be opened
and worked on directly.  This root file imports the represented paper statements
directly rather than routing through extra wrapper indexes.
-/

import DictatorshipTesting.Basic
import DictatorshipTesting.BasicFacts
import DictatorshipTesting.SetFacts
import DictatorshipTesting.SetFacts.Fact_sub_sd_SetMinusSymmDiff
import DictatorshipTesting.AlgebraicProperty


/- Paper-numbered files currently represented in Lean. -/
import DictatorshipTesting.Paper.S01_Thm1_01_MainIntro
import DictatorshipTesting.Paper.Defs.S02_Def2_01_FiniteSeedTester
import DictatorshipTesting.Paper.S02_Thm2_01_BooleanU1Classification
import DictatorshipTesting.Paper.S02_Thm2_02_FKNStability
import DictatorshipTesting.Paper.S02_Lem2_03_CubeCharOrthonormality
import DictatorshipTesting.Paper.S02_Lem2_03_CubeFourierExpansion
import DictatorshipTesting.Paper.S02_Lem2_03_CubeParsevalIdentity
import DictatorshipTesting.Paper.S02_Lem2_03_CubeParseval
import DictatorshipTesting.Paper.Defs.S02_Def2_02a_CubeLowDegreeOnePart
import DictatorshipTesting.Paper.Defs.S02_Def2_02b_CubeHighDegreeEnergy
import DictatorshipTesting.Paper.S03_Lem3_01_DictatorToJunta
import DictatorshipTesting.Paper.S03_Lem3_02_PerfectCompleteness
import DictatorshipTesting.Paper.S04_Lem4_01_CubeSquare
import DictatorshipTesting.Paper.Defs.S04_Def4_01a_IsMatchingLocalDegreeOne
import DictatorshipTesting.Paper.Defs.S04_Def4_01b_MatchingLocalHighDegreeEnergy
import DictatorshipTesting.Paper.Defs.S04_Def4_02a_MatchingLocalProjection
import DictatorshipTesting.Paper.Defs.S04_Def4_02b_MatchingLocalProjectionError
import DictatorshipTesting.Paper.S04_Lem4_02_PMIndependentOfRepresentatives
import DictatorshipTesting.Paper.S04_Prop4_03_MatchingLocalTruncationOrthogonalProjection
import DictatorshipTesting.Paper.S04_Lem4_04_TijLocalDegree
import DictatorshipTesting.Paper.S04_Cor4_05_U1Local
import DictatorshipTesting.Paper.S04_Thm4_06_MatchingGap
import DictatorshipTesting.Paper.S04_Lem4_07_TrialCubeCoordinates
import DictatorshipTesting.Paper.S04_Prop4_08_SquareEnergyControlsGlobalDegree
import DictatorshipTesting.Paper.S04_Lem4_09_OneTrialSoundness
import DictatorshipTesting.Paper.S04_Lem4_10_IndependentRepetitionAndAmplification
import DictatorshipTesting.Paper.Defs.S05_Def5_01_YoungDiagramsAndBoxes
import DictatorshipTesting.Paper.Defs.S05_Def5_02_RemovableCorners
import DictatorshipTesting.Paper.Defs.S05_Def5_03_StandardTableaux
import DictatorshipTesting.Paper.Defs.S05_Def5_04_TableauCoordinateSpace
import DictatorshipTesting.Paper.Defs.S05_Def5_05_ContentAndAdjacentOperators
import DictatorshipTesting.Paper.S05_Lem5_01_AdjacentTranspositionsInYoungsBasis
import DictatorshipTesting.Paper.S05_Lem5_02_TypeAAdjacentWordPresentation
import DictatorshipTesting.Paper.S05_Thm5_03_YoungOrthogonalAction
import DictatorshipTesting.Paper.S05_Lem5_04_JucysMurphyRecurrences
import DictatorshipTesting.Paper.S05_Thm5_05_JucysMurphyContentAction
import DictatorshipTesting.Paper.S05_Lem5_06_DiagonalContentEigenspaces
import DictatorshipTesting.Paper.S05_Lem5_07_ConnectednessOfStandardTableaux
import DictatorshipTesting.Paper.S05_Lem5_08_YoungBasisScalarCommutant
import DictatorshipTesting.Paper.Defs.S05_Def5_06a_YoungBlock
import DictatorshipTesting.Paper.Defs.S05_Def5_06b_YoungMatrixCoefficients
import DictatorshipTesting.Paper.Defs.S05_Def5_06c_YoungBlockComponentsAndEnergies
import DictatorshipTesting.Paper.S05_Lem5_09_YoungMatrixCoefficientOrthogonality
import DictatorshipTesting.Paper.S05_Lem5_10_YoungTableauSumOfSquares
import DictatorshipTesting.Paper.S05_Lem5_11_RegularYoungBlockDecomposition
import DictatorshipTesting.Paper.S05_Lem5_12_DegreeOneYoungBlockIdentification
import DictatorshipTesting.Paper.Defs.S05_Def5_07a_TwoBoxRemovals
import DictatorshipTesting.Paper.Defs.S05_Def5_07b_SignedTwoBoxRemovals
import DictatorshipTesting.Paper.Defs.S05_Def5_07c_OneBoxRemovals
import DictatorshipTesting.Paper.Defs.S05_Def5_08_SignedTwoBoxExtensionSpaces
import DictatorshipTesting.Paper.S05_Lem5_13_SignedTwoBoxOrthogonalBranching
import DictatorshipTesting.Paper.Defs.S05_Def5_09_OneBoxDeletionSpaces
import DictatorshipTesting.Paper.S05_Lem5_14_OneBoxDecompositionAndDeletion
import DictatorshipTesting.Paper.Defs.S05_Def5_10a_EvenSignPatternMultiset
import DictatorshipTesting.Paper.Defs.S05_Def5_10b_OddSignPatternMultiset
import DictatorshipTesting.Paper.S05_Lem5_15_BranchingDimensionsAndSignPatternCardinalities
import DictatorshipTesting.Paper.Defs.S05_Def5_11a_MatchingCharacters
import DictatorshipTesting.Paper.Defs.S05_Def5_11b_IsMatchingEigenvectorEven
import DictatorshipTesting.Paper.Defs.S05_Def5_11c_IsMatchingEigenvectorOdd
import DictatorshipTesting.Paper.S05_Lem5_16_MatchingSubgroupEigenbasis
import DictatorshipTesting.Paper.S05_Lem5_17_LocalTruncationOnAMatchingCharacter
import DictatorshipTesting.Paper.S05_Lem5_18_TraceOfOneLocalTruncationOnOneYoungBlock
import DictatorshipTesting.Paper.Defs.S05_Def5_12a_MatchingIdempotents
import DictatorshipTesting.Paper.S05_Lem5_19_LocalTruncationAsConvolution
import DictatorshipTesting.Paper.S05_Lem5_20_CentralAveragedRejection
import DictatorshipTesting.Paper.S05_Lem5_21_BlockScalarOfTheAveragedRejection
import DictatorshipTesting.Paper.Defs.S05_Def5_12b_GroupAlgebraAction
import DictatorshipTesting.Paper.Defs.S05_Def5_12c_AveragedHighMatchingElement
import DictatorshipTesting.Paper.Defs.S05_Def5_12d_TableauOperatorTrace
import DictatorshipTesting.Paper.S05_Lem5_22_GlobalWeightedMatchingIdentity
import DictatorshipTesting.Paper.S05_Lem5_23_CountingOneMoreMatchingEdge
import DictatorshipTesting.Paper.S05_Lem5_24_WeightZeroEntriesAreNeverAMajority
import DictatorshipTesting.Paper.S05_Lem5_25_EvenCertificate
import DictatorshipTesting.Paper.S05_Lem5_26_OddCertificate

/-
Direct reverse imports:
- None.
-/
