import AlgebraicLibrary.BooleanCube.Basic
import Mathlib.Algebra.Group.End

/-! Ordered matchings and their associated products of disjoint transpositions. -/

noncomputable section

namespace AlgebraicLibrary

/-- A finite ordered matching. No decidable-equality assumption is stored in
the combinatorial data itself. -/
structure OrderedMatching (α : Type*) where
  edgeCount : ℕ
  left : Fin edgeCount → α
  right : Fin edgeCount → α
  left_ne_right : ∀ r, left r ≠ right r
  edges_disjoint :
    ∀ {r s : Fin edgeCount}, r ≠ s →
      left r ≠ left s ∧ left r ≠ right s ∧
        right r ≠ left s ∧ right r ≠ right s

namespace OrderedMatching

/-- Boolean labels on the edges of an ordered matching. -/
abbrev EdgeCube {α : Type*} (M : OrderedMatching α) := Cube (Fin M.edgeCount)

/-- The transposition associated to one edge. -/
def edgeSwap {α : Type*} [DecidableEq α] (M : OrderedMatching α)
    (r : Fin M.edgeCount) : Equiv.Perm α :=
  Equiv.swap (M.left r) (M.right r)

/-- The `r`th edge transposition when its bit is on, and identity otherwise. -/
def edgePerm {α : Type*} [DecidableEq α] (M : OrderedMatching α)
    (x : M.EdgeCube) (r : Fin M.edgeCount) : Equiv.Perm α :=
  if x r then M.edgeSwap r else 1

/-- The cube element generated by the matching transpositions. -/
def tau {α : Type*} [DecidableEq α] (M : OrderedMatching α)
    (x : M.EdgeCube) : Equiv.Perm α :=
  (List.ofFn fun r : Fin M.edgeCount => M.edgePerm x r).prod

/-- Membership in the two endpoints of one ordered matching edge. -/
def InEdge {α : Type*} (M : OrderedMatching α)
    (r : Fin M.edgeCount) (a : α) : Prop :=
  a = M.left r ∨ a = M.right r

/-- Relabel every endpoint of an ordered matching by a permutation. -/
def relabel {α : Type*} [DecidableEq α]
    (σ : Equiv.Perm α) (M : OrderedMatching α) : OrderedMatching α where
  edgeCount := M.edgeCount
  left r := σ (M.left r)
  right r := σ (M.right r)
  left_ne_right r := by
    intro h
    exact M.left_ne_right r (σ.injective h)
  edges_disjoint := by
    intro r s hrs
    rcases M.edges_disjoint hrs with ⟨hll, hlr, hrl, hrr⟩
    exact ⟨fun h => hll (σ.injective h),
      fun h => hlr (σ.injective h),
      fun h => hrl (σ.injective h),
      fun h => hrr (σ.injective h)⟩

end OrderedMatching

end AlgebraicLibrary
