import DictatorshipTesting.Paper.Defs.S02_Def2_01_BoolFn
import DictatorshipTesting.Paper.Defs.S02_Def2_02_BoolToReal
import DictatorshipTesting.Paper.Defs.S02_Def2_03_BoolFnToReal
import DictatorshipTesting.Paper.Defs.S02_Def2_04_IsImageDictator
import DictatorshipTesting.Paper.Defs.S02_Def2_05_IsPreimageDictator
import DictatorshipTesting.Paper.Defs.S02_Def2_06_IsDictator
import DictatorshipTesting.Paper.Defs.S02_Def2_07_HammingDist
import DictatorshipTesting.Paper.Defs.S02_Def2_08_DistToDictators
import DictatorshipTesting.Paper.Defs.S01_Def1_01_OracleTester
import DictatorshipTesting.Paper.Defs.S02_Def2_09_OneCosetReal
import DictatorshipTesting.Paper.Defs.S02_Def2_10_U1
import DictatorshipTesting.Paper.Defs.S02_Def2_11_L2DistSq
import DictatorshipTesting.Paper.Defs.S02_Def2_12_L2DistSqToU1
import DictatorshipTesting.Paper.Defs.S02_Def2_13_Cube
import DictatorshipTesting.Paper.Defs.S02_Def2_14_CubeChar
import DictatorshipTesting.Paper.Defs.S02_Def2_15_CubeFlip
import DictatorshipTesting.Paper.Defs.S02_Def2_16_CubeExpectation
import DictatorshipTesting.Paper.Defs.S02_Def2_17_CubeFourierCoeff
import DictatorshipTesting.Paper.Defs.S02_Def2_18_CubeXor
import DictatorshipTesting.Paper.Defs.S02_Def2_19_CubeZero
import DictatorshipTesting.Paper.Defs.S02_Def2_20_CubeDelta
import DictatorshipTesting.Paper.Defs.S02_Def2_21_CubeDirectionsDisjoint
import DictatorshipTesting.Paper.Defs.S02_Def2_22_IsCubeConstant
import DictatorshipTesting.Paper.Defs.S02_Def2_23_IsCubeJuntaAt
import DictatorshipTesting.Paper.Defs.S02_Def2_24_IsCubeOneJunta
import DictatorshipTesting.Paper.Defs.S03_Def3_01_OrderedMatching
import DictatorshipTesting.Paper.Defs.S03_Def3_02_OrderedMatchingEdgeSwap
import DictatorshipTesting.Paper.Defs.S03_Def3_03_OrderedMatchingEdgePerm
import DictatorshipTesting.Paper.Defs.S03_Def3_04_OrderedMatchingTau
import DictatorshipTesting.Paper.Defs.S03_Def3_05_MatchingCubeRestriction
import DictatorshipTesting.Paper.Defs.S03_Def3_06_CubeDirectionColor
import DictatorshipTesting.Paper.Defs.S03_Def3_07_CubeColorU
import DictatorshipTesting.Paper.Defs.S03_Def3_08_CubeColorV
import DictatorshipTesting.Paper.Defs.S03_Def3_09_MatchingTrialDelta
import DictatorshipTesting.Paper.Defs.S03_Def3_10_MatchingTrialDeltaReal
import DictatorshipTesting.Paper.Defs.S03_Def3_11_CubeLowDegreeOnePart
import DictatorshipTesting.Paper.Defs.S03_Def3_12_CubeHighDegreeEnergy
import DictatorshipTesting.Paper.Defs.S03_Def3_13_CubeSquareEnergy
import DictatorshipTesting.Paper.Defs.S03_Def3_14_PermInner
import DictatorshipTesting.Paper.Defs.S03_Def3_15_IsMatchingLocalDegreeOne
import DictatorshipTesting.Paper.Defs.S03_Def3_16_MatchingLocalHighDegreeEnergy
import DictatorshipTesting.Paper.Defs.S03_Def3_17_MatchingLocalProjection
import DictatorshipTesting.Paper.Defs.S03_Def3_18_MatchingLocalProjectionError
import DictatorshipTesting.Paper.Defs.S03_Def3_19_NearPerfectMatching
import DictatorshipTesting.Paper.S03_Inst3_20_NearPerfectMatchingFintype
import DictatorshipTesting.Paper.S03_Inst3_21_NearPerfectMatchingNonempty
import DictatorshipTesting.Paper.Defs.S03_Def3_22_NearPerfectMatchingToOrdered
import DictatorshipTesting.Paper.Defs.S03_Def3_23_MatchingMeanProjectionError
import DictatorshipTesting.Paper.Defs.S03_Def3_24_OneTrialDeltaSqExpectation
import DictatorshipTesting.Paper.Defs.S03_Def3_25_OneTrialRejectProbability
import DictatorshipTesting.Paper.Defs.S03_Def3_26_MatchingLowConvolution
import DictatorshipTesting.Paper.Defs.S03_Def3_27_MatchingHighConvolution
import DictatorshipTesting.Paper.Defs.S05_IntDef_YoungDiagram
import DictatorshipTesting.Paper.S05_IntInst_YoungDiagramFintype
import DictatorshipTesting.Paper.Defs.S05_IntDef_YoungRow
import DictatorshipTesting.Paper.Defs.S05_IntDef_YoungCells
import DictatorshipTesting.Paper.Defs.S05_IntDef_YoungHookLength
import DictatorshipTesting.Paper.Defs.S05_IntDef_YoungDimNat
import DictatorshipTesting.Paper.Defs.S05_IntDef_YoungDim
import DictatorshipTesting.Paper.Defs.S05_IntDef_IsOneRow
import DictatorshipTesting.Paper.Defs.S05_IntDef_IsStandard
import DictatorshipTesting.Paper.Defs.S05_IntDef_IsYoungSubdiagram
import DictatorshipTesting.Paper.Defs.S05_IntDef_IsHorizontalTwoStripChild
import DictatorshipTesting.Paper.Defs.S05_IntDef_IsVerticalTwoStripChild
import DictatorshipTesting.Paper.Defs.S05_IntDef_IsOneBoxChild
import DictatorshipTesting.Paper.Defs.S05_IntDef_HorizontalTwoStripChildren
import DictatorshipTesting.Paper.Defs.S05_IntDef_VerticalTwoStripChildren
import DictatorshipTesting.Paper.Defs.S05_IntDef_OneBoxChildren
import DictatorshipTesting.Paper.Defs.S05_IntDef_HorizontalTwoStripChildrenEven
import DictatorshipTesting.Paper.Defs.S05_IntDef_VerticalTwoStripChildrenEven
import DictatorshipTesting.Paper.Defs.S05_IntDef_OneBoxChildrenOdd
import DictatorshipTesting.Paper.Defs.S05_IntDef_ZEven
import DictatorshipTesting.Paper.Defs.S05_IntDef_HEven
import DictatorshipTesting.Paper.Defs.S05_IntDef_HOdd
import DictatorshipTesting.Paper.Defs.S05_IntDef_MatchingSpectralGapConstant

/-
Direct reverse imports:
- `DictatorshipTesting.Paper.S02_Int_CubeCharFlip`
- `DictatorshipTesting.Paper.S02_Int_CubeCharMulSelf`
- `DictatorshipTesting.Paper.S02_Int_CubeCharXor`
- `DictatorshipTesting.Paper.S02_Int_CubeFlipInvolutive`
- `DictatorshipTesting.Paper.S04_Int_CubeHighDegreeLinear`
- `DictatorshipTesting.Paper.S03_Int_OrderedMatchingTauDepends`
- `DictatorshipTesting.Paper.S05_Int_SpectralBridgeRepresentationInputs`
- `DictatorshipTesting.Paper.S05_Int_YoungDiagramCorners`
- `DictatorshipTesting.Paper.S01_Thm1_01_MainIntro`
- `DictatorshipTesting.Paper.S02_Lem2_03_CubeFourierExpansion`
- `DictatorshipTesting.Paper.S02_Thm2_01_BooleanU1Classification`
- `DictatorshipTesting.Paper.S02_Thm2_02_FKNStability`
- `DictatorshipTesting.Paper.S04_Lem4_13_OneTrialSoundness`
- `DictatorshipTesting.Paper.S04_Thm4_10_MatchingGap`
- `DictatorshipTesting.Paper.Defs.S05_Def5_01_YoungDiagramsAndBoxes`
- `DictatorshipTesting.Paper.Defs.S05_Def5_13_EvenSignPatternMultiset`
- `DictatorshipTesting.Paper.Defs.S05_Def5_15_MatchingCharacters`
- `DictatorshipTesting.Paper.S05_Lem5_21_CountingOneMoreMatchingEdge`
-/

/-!
This file is an import aggregator for paper definitions.
It should contain no `def`, `abbrev`, `structure`, `class`, `instance`,
`inductive`, or theorem declarations.
-/
