import DictatorshipTesting.Paper.S02_Def2_01_BoolFn
import DictatorshipTesting.Paper.S02_Def2_02_BoolToReal
import DictatorshipTesting.Paper.S02_Def2_03_BoolFnToReal
import DictatorshipTesting.Paper.S02_Def2_04_IsImageDictator
import DictatorshipTesting.Paper.S02_Def2_05_IsPreimageDictator
import DictatorshipTesting.Paper.S02_Def2_06_IsDictator
import DictatorshipTesting.Paper.S02_Def2_07_HammingDist
import DictatorshipTesting.Paper.S02_Def2_08_DistToDictators
import DictatorshipTesting.Paper.S01_Def1_01_OracleTester
import DictatorshipTesting.Paper.S02_Def2_09_OneCosetReal
import DictatorshipTesting.Paper.S02_Def2_10_U1
import DictatorshipTesting.Paper.S02_Def2_11_L2DistSq
import DictatorshipTesting.Paper.S02_Def2_12_L2DistSqToU1
import DictatorshipTesting.Paper.S02_Def2_13_Cube
import DictatorshipTesting.Paper.S02_Def2_14_CubeChar
import DictatorshipTesting.Paper.S02_Def2_15_CubeFlip
import DictatorshipTesting.Paper.S02_Def2_16_CubeExpectation
import DictatorshipTesting.Paper.S02_Def2_17_CubeFourierCoeff
import DictatorshipTesting.Paper.S02_Def2_18_CubeXor
import DictatorshipTesting.Paper.S02_Def2_19_CubeZero
import DictatorshipTesting.Paper.S02_Def2_20_CubeDelta
import DictatorshipTesting.Paper.S02_Def2_21_CubeDirectionsDisjoint
import DictatorshipTesting.Paper.S02_Def2_22_IsCubeConstant
import DictatorshipTesting.Paper.S02_Def2_23_IsCubeJuntaAt
import DictatorshipTesting.Paper.S02_Def2_24_IsCubeOneJunta
import DictatorshipTesting.Paper.S03_Def3_01_OrderedMatching
import DictatorshipTesting.Paper.S03_Def3_02_OrderedMatchingEdgeSwap
import DictatorshipTesting.Paper.S03_Def3_03_OrderedMatchingEdgePerm
import DictatorshipTesting.Paper.S03_Def3_04_OrderedMatchingTau
import DictatorshipTesting.Paper.S03_Def3_05_MatchingCubeRestriction
import DictatorshipTesting.Paper.S03_Def3_06_CubeDirectionColor
import DictatorshipTesting.Paper.S03_Def3_07_CubeColorU
import DictatorshipTesting.Paper.S03_Def3_08_CubeColorV
import DictatorshipTesting.Paper.S03_Def3_09_MatchingTrialDelta
import DictatorshipTesting.Paper.S03_Def3_10_MatchingTrialDeltaReal
import DictatorshipTesting.Paper.S03_Def3_11_CubeLowDegreeOnePart
import DictatorshipTesting.Paper.S03_Def3_12_CubeHighDegreeEnergy
import DictatorshipTesting.Paper.S03_Def3_13_CubeSquareEnergy
import DictatorshipTesting.Paper.S03_Def3_14_PermInner
import DictatorshipTesting.Paper.S03_Def3_15_IsMatchingLocalDegreeOne
import DictatorshipTesting.Paper.S03_Def3_16_MatchingLocalHighDegreeEnergy
import DictatorshipTesting.Paper.S03_Def3_17_MatchingLocalProjection
import DictatorshipTesting.Paper.S03_Def3_18_MatchingLocalProjectionError
import DictatorshipTesting.Paper.S03_Def3_19_NearPerfectMatching
import DictatorshipTesting.Paper.S03_Inst3_20_NearPerfectMatchingFintype
import DictatorshipTesting.Paper.S03_Inst3_21_NearPerfectMatchingNonempty
import DictatorshipTesting.Paper.S03_Def3_22_NearPerfectMatchingToOrdered
import DictatorshipTesting.Paper.S03_Def3_23_MatchingMeanProjectionError
import DictatorshipTesting.Paper.S03_Def3_24_OneTrialDeltaSqExpectation
import DictatorshipTesting.Paper.S03_Def3_25_OneTrialRejectProbability
import DictatorshipTesting.Paper.S03_Def3_26_MatchingLowConvolution
import DictatorshipTesting.Paper.S03_Def3_27_MatchingHighConvolution
import DictatorshipTesting.Paper.Aux_Def_YoungDiagram
import DictatorshipTesting.Paper.Aux_Inst_YoungDiagramFintype
import DictatorshipTesting.Paper.Aux_Def_YoungRow
import DictatorshipTesting.Paper.Aux_Def_YoungCells
import DictatorshipTesting.Paper.Aux_Def_YoungHookLength
import DictatorshipTesting.Paper.Aux_Def_YoungDimNat
import DictatorshipTesting.Paper.Aux_Def_YoungDim
import DictatorshipTesting.Paper.Aux_Def_IsOneRow
import DictatorshipTesting.Paper.Aux_Def_IsStandard
import DictatorshipTesting.Paper.Aux_Def_IsYoungSubdiagram
import DictatorshipTesting.Paper.Aux_Def_IsHorizontalTwoStripChild
import DictatorshipTesting.Paper.Aux_Def_IsVerticalTwoStripChild
import DictatorshipTesting.Paper.Aux_Def_IsOneBoxChild
import DictatorshipTesting.Paper.Aux_Def_HorizontalTwoStripChildren
import DictatorshipTesting.Paper.Aux_Def_VerticalTwoStripChildren
import DictatorshipTesting.Paper.Aux_Def_OneBoxChildren
import DictatorshipTesting.Paper.Aux_Def_HorizontalTwoStripChildrenEven
import DictatorshipTesting.Paper.Aux_Def_VerticalTwoStripChildrenEven
import DictatorshipTesting.Paper.Aux_Def_OneBoxChildrenOdd
import DictatorshipTesting.Paper.Aux_Def_ZEven
import DictatorshipTesting.Paper.Aux_Def_HEven
import DictatorshipTesting.Paper.Aux_Def_HOdd
import DictatorshipTesting.Paper.Aux_Def_MatchingSpectralGapConstant

/-
Direct reverse imports:
- `DictatorshipTesting.Paper.Aux_CubeCharFlip`
- `DictatorshipTesting.Paper.Aux_CubeCharMulSelf`
- `DictatorshipTesting.Paper.Aux_CubeCharXor`
- `DictatorshipTesting.Paper.Aux_CubeFlipInvolutive`
- `DictatorshipTesting.Paper.Aux_CubeHighDegreeLinear`
- `DictatorshipTesting.Paper.Aux_OneTrialRejectProbabilityLowerBound`
- `DictatorshipTesting.Paper.Aux_OrderedMatchingTauDepends`
- `DictatorshipTesting.Paper.Aux_SpectralBridgeRepresentationInputs`
- `DictatorshipTesting.Paper.Aux_YoungDiagramCorners`
- `DictatorshipTesting.Paper.S01_Thm1_01_MainIntro`
- `DictatorshipTesting.Paper.S02_Lem2_03_CubeFourierExpansion`
- `DictatorshipTesting.Paper.S02_Thm2_01_BooleanU1Classification`
- `DictatorshipTesting.Paper.S02_Thm2_02_FKNStability`
- `DictatorshipTesting.Paper.S04_Thm4_10_MatchingGap`
- `DictatorshipTesting.Paper.Aux_Def_YoungDiagramsAndBoxes`
- `DictatorshipTesting.Paper.S05_Def5_19_EvenSignPatternMultiset`
- `DictatorshipTesting.Paper.S05_Def5_24_MatchingCharacters`
- `DictatorshipTesting.Paper.S05_Lem5_44_CountingOneMoreMatchingEdge`
-/

/-!
This file is an import aggregator for paper definitions.
It should contain no `def`, `abbrev`, `structure`, `class`, `instance`,
`inductive`, or theorem declarations.
-/
