import DictatorshipTesting.Paper.S03_Def3_03_OrderedMatchingEdgePerm

/-!
Definition file for `OrderedMatching.tau`.

This file contains one primary reusable declaration split out of
`DictatorshipTesting.Paper.Defs`.
-/

noncomputable section

open scoped BigOperators

namespace DictatorshipTesting

/-- The cube element `tau_x` generated by the matching transpositions. -/
def OrderedMatching.tau {α : Type*} [DecidableEq α]
    (M : OrderedMatching α) (x : Cube M.edgeCount) : Perm α :=
  (List.ofFn fun r : Fin M.edgeCount => M.edgePerm x r).prod

end DictatorshipTesting
