import Mathlib.Data.List.Pairwise
import Mathlib.Data.List.FinRange
import DictatorshipTesting.Paper.S05_Int_YoungOrthogonal

/-
Direct reverse imports:
- `DictatorshipTesting`
- `DictatorshipTesting.Paper.S05_Lem5_16_YoungBasisScalarCommutant`
-/

/-!
Paper statement: Lemma 5.3
Title: Connectedness of standard tableaux
Status: proven internally

The proof first establishes the finite-list linear-extension argument: adjacent
swaps of incomparable neighboring elements preserve linear extensions, and any
two linear extensions of the same finite support are connected by an explicit
path of such swaps.  It then specializes box orders to standard Young tableaux
and transports every list-level edge to a valid adjacent tableau swap.
-/

noncomputable section

namespace DictatorshipTesting

variable {α : Type*}

/-- Two elements are incomparable for a strict order-like relation `lt`. -/
def Incomparable (lt : α -> α -> Prop) (a b : α) : Prop :=
  ¬ lt a b ∧ ¬ lt b a

/-- A list model for a linear extension of a finite strict poset.  The list has
no duplicates, and no later entry is required by `lt` to precede an earlier
entry. -/
def IsLinearExtension (lt : α -> α -> Prop) (xs : List α) : Prop :=
  xs.Nodup ∧ xs.Pairwise (fun a b => ¬ lt b a)

/-- One adjacent swap of incomparable neighboring entries. -/
def AdjacentIncomparableSwap (lt : α -> α -> Prop) (xs ys : List α) : Prop :=
  ∃ pre post a b,
    Incomparable lt a b ∧
      xs = pre ++ a :: b :: post ∧
      ys = pre ++ b :: a :: post

/-- Reachability generated by adjacent swaps of incomparable neighboring
entries.  This is the abstract graph relation that the tableau specialization
should eventually instantiate. -/
def LinearExtensionSwapReachable (lt : α -> α -> Prop) (xs ys : List α) : Prop :=
  Relation.ReflTransGen (AdjacentIncomparableSwap lt) xs ys

theorem adjacentIncomparableSwap_symm {lt : α -> α -> Prop} {xs ys : List α}
    (h : AdjacentIncomparableSwap lt xs ys) :
    AdjacentIncomparableSwap lt ys xs := by
  rcases h with ⟨pre, post, a, b, hinc, rfl, rfl⟩
  exact ⟨pre, post, b, a, ⟨hinc.2, hinc.1⟩, rfl, rfl⟩

theorem nodup_adjacent_swap {pre post : List α} {a b : α}
    (h : (pre ++ a :: b :: post).Nodup) :
    (pre ++ b :: a :: post).Nodup := by
  have hp : (pre ++ b :: a :: post).Perm (pre ++ a :: b :: post) := by
    exact List.Perm.append_left _ (List.Perm.swap _ _ _)
  exact hp.nodup_iff.mpr h

/-- Swapping adjacent incomparable entries preserves the list-level
linear-extension predicate. -/
theorem isLinearExtension_adjacent_swap {lt : α -> α -> Prop}
    {pre post : List α} {a b : α}
    (hlin : IsLinearExtension lt (pre ++ a :: b :: post))
    (hinc : Incomparable lt a b) :
    IsLinearExtension lt (pre ++ b :: a :: post) := by
  classical
  rcases hlin with ⟨hnodup, hpair⟩
  refine ⟨nodup_adjacent_swap hnodup, ?_⟩
  let R : α -> α -> Prop := fun x y => ¬ lt y x
  change (pre ++ b :: a :: post).Pairwise R
  change (pre ++ a :: b :: post).Pairwise R at hpair
  rw [List.pairwise_append] at hpair ⊢
  rcases hpair with ⟨hpre, htail, hcross⟩
  rw [List.pairwise_cons] at htail
  rcases htail with ⟨ha_all, hbtail⟩
  rw [List.pairwise_cons] at hbtail
  rcases hbtail with ⟨hb_post, hpost⟩
  refine ⟨hpre, ?_, ?_⟩
  · rw [List.pairwise_cons]
    refine ⟨?_, ?_⟩
    · intro y hy
      rcases List.mem_cons.mp hy with rfl | hy
      · simpa [R] using hinc.1
      · exact hb_post y hy
    · rw [List.pairwise_cons]
      refine ⟨?_, hpost⟩
      intro y hy
      exact ha_all y (by simp [hy])
  intro x hx y hy
  have hy' : y ∈ a :: b :: post := by
    simp only [List.mem_cons] at hy ⊢
    tauto
  exact hcross x hx y hy'

/-- The same preservation statement phrased for one abstract adjacent-swap
edge. -/
theorem isLinearExtension_of_adjacentIncomparableSwap {lt : α -> α -> Prop}
    {xs ys : List α}
    (hstep : AdjacentIncomparableSwap lt xs ys)
    (hlin : IsLinearExtension lt xs) :
    IsLinearExtension lt ys := by
  rcases hstep with ⟨pre, post, a, b, hinc, rfl, rfl⟩
  exact isLinearExtension_adjacent_swap hlin hinc

/-- An adjacent incomparable swap remains such a swap after adding the same
entry at the front of both lists. -/
theorem adjacentIncomparableSwap_cons {lt : α -> α -> Prop}
    (c : α) {xs ys : List α}
    (hstep : AdjacentIncomparableSwap lt xs ys) :
    AdjacentIncomparableSwap lt (c :: xs) (c :: ys) := by
  rcases hstep with ⟨pre, post, a, b, hinc, rfl, rfl⟩
  exact ⟨c :: pre, post, a, b, hinc, by simp, by simp⟩

/-- A path of adjacent incomparable swaps remains a path after adding the same
entry at the front of every list. -/
theorem reflTransGen_adjacentIncomparableSwap_cons {lt : α -> α -> Prop}
    (c : α) {xs ys : List α}
    (hreach : LinearExtensionSwapReachable lt xs ys) :
    LinearExtensionSwapReachable lt (c :: xs) (c :: ys) := by
  induction hreach with
  | refl => exact Relation.ReflTransGen.refl
  | tail hxy hyz ih =>
      exact ih.tail (adjacentIncomparableSwap_cons c hyz)

/-- The linear-extension predicate is preserved along a finite path of
adjacent incomparable swaps. -/
theorem isLinearExtension_of_swapReachable {lt : α -> α -> Prop}
    {xs ys : List α}
    (hreach : LinearExtensionSwapReachable lt xs ys)
    (hlin : IsLinearExtension lt xs) :
    IsLinearExtension lt ys := by
  induction hreach with
  | refl => exact hlin
  | tail hxy hyz ih =>
      exact isLinearExtension_of_adjacentIncomparableSwap hyz ih

/-- One adjacent swap preserves the multiset of list entries. -/
theorem perm_of_adjacentIncomparableSwap {lt : α -> α -> Prop}
    {xs ys : List α}
    (hstep : AdjacentIncomparableSwap lt xs ys) :
    xs.Perm ys := by
  rcases hstep with ⟨pre, post, a, b, _hinc, rfl, rfl⟩
  exact List.Perm.append_left pre (List.Perm.swap b a post)

/-- A finite path of adjacent swaps preserves the multiset of list entries. -/
theorem perm_of_swapReachable {lt : α -> α -> Prop}
    {xs ys : List α}
    (hreach : LinearExtensionSwapReachable lt xs ys) :
    xs.Perm ys := by
  induction hreach with
  | refl => exact List.Perm.refl _
  | tail hxy hyz ih =>
      exact ih.trans (perm_of_adjacentIncomparableSwap hyz)

/-- If two linear extensions have the same entries and the target starts with
`b`, every entry crossed while moving `b` to the front of the source is
incomparable with `b`. -/
theorem linearExtension_crossed_elements_incomparable
    [DecidableEq α] {lt : α -> α -> Prop}
    {pre post bs : List α} {b : α}
    (hsource : IsLinearExtension lt (pre ++ b :: post))
    (htarget : IsLinearExtension lt (b :: bs))
    (hperm : (pre ++ b :: post).Perm (b :: bs)) :
    ∀ a ∈ pre, Incomparable lt a b := by
  intro a ha
  have hsourcePair := hsource.2
  rw [List.pairwise_append] at hsourcePair
  rcases hsourcePair with ⟨_hpre, _htail, hcross⟩
  have hnot_ba : ¬ lt b a :=
    hcross a ha b (by simp)
  have hab_ne : a ≠ b := by
    exact (List.nodup_append.mp hsource.1).2.2
      a ha b (by simp)
  have ha_source : a ∈ pre ++ b :: post := by
    exact List.mem_append_left _ ha
  have ha_target : a ∈ b :: bs :=
    hperm.mem_iff.mp ha_source
  have ha_bs : a ∈ bs := by
    exact (List.mem_cons.mp ha_target).resolve_left hab_ne
  have htargetPair := htarget.2
  rw [List.pairwise_cons] at htargetPair
  have hnot_ab : ¬ lt a b := htargetPair.1 a ha_bs
  exact ⟨hnot_ab, hnot_ba⟩

/-- If `b` is incomparable with every entry of `pre`, repeated adjacent swaps
move `b` from immediately after `pre` to the front. -/
theorem reflTransGen_adjacentIncomparableSwap_move_left
    {lt : α -> α -> Prop} (pre post : List α) (b : α)
    (hinc : ∀ a ∈ pre, Incomparable lt a b) :
    LinearExtensionSwapReachable lt
      (pre ++ b :: post) (b :: pre ++ post) := by
  induction pre with
  | nil =>
      exact Relation.ReflTransGen.refl
  | cons a pre ih =>
      have hinc_a : Incomparable lt a b := hinc a (by simp)
      have hinc_pre : ∀ c ∈ pre, Incomparable lt c b := by
        intro c hc
        exact hinc c (by simp [hc])
      have htail := ih hinc_pre
      have hlift := reflTransGen_adjacentIncomparableSwap_cons a htail
      have hstep :
          AdjacentIncomparableSwap lt
            (a :: b :: pre ++ post) (b :: a :: pre ++ post) := by
        exact ⟨[], pre ++ post, a, b, hinc_a, by simp, by simp⟩
      exact hlift.tail hstep

/-- Any two list-level linear extensions with the same finite entries are
connected by adjacent swaps of incomparable neighboring elements. -/
theorem linearExtensions_connected_by_adjacent_incomparable_swaps
    [DecidableEq α] (lt : α -> α -> Prop)
    (xs ys : List α)
    (hxs : IsLinearExtension lt xs)
    (hys : IsLinearExtension lt ys)
    (hperm : xs.Perm ys) :
    LinearExtensionSwapReachable lt xs ys := by
  induction ys generalizing xs with
  | nil =>
      have hnil : xs = [] := hperm.eq_nil
      subst xs
      exact Relation.ReflTransGen.refl
  | cons b bs ih =>
      have hb_source : b ∈ xs :=
        hperm.mem_iff.mpr (by simp)
      rcases List.append_of_mem hb_source with ⟨pre, post, rfl⟩
      have hinc : ∀ a ∈ pre, Incomparable lt a b :=
        linearExtension_crossed_elements_incomparable hxs hys hperm
      have hmove :
          LinearExtensionSwapReachable lt
            (pre ++ b :: post) (b :: pre ++ post) :=
        reflTransGen_adjacentIncomparableSwap_move_left pre post b hinc
      have hmovedLin : IsLinearExtension lt (b :: pre ++ post) :=
        isLinearExtension_of_swapReachable hmove hxs
      have hmovedPerm :
          (pre ++ b :: post).Perm (b :: pre ++ post) :=
        perm_of_swapReachable hmove
      have hconsPerm : (b :: pre ++ post).Perm (b :: bs) :=
        hmovedPerm.symm.trans hperm
      have htailPerm : (pre ++ post).Perm bs :=
        hconsPerm.cons_inv
      have hsourceTail : IsLinearExtension lt (pre ++ post) :=
        ⟨hmovedLin.1.of_cons, hmovedLin.2.of_cons⟩
      have htargetTail : IsLinearExtension lt bs :=
        ⟨hys.1.of_cons, hys.2.of_cons⟩
      have htailReach :
          LinearExtensionSwapReachable lt (pre ++ post) bs :=
        ih (pre ++ post) hsourceTail htargetTail htailPerm
      exact hmove.trans
        (reflTransGen_adjacentIncomparableSwap_cons b htailReach)

/-- The strict row-or-column order on boxes of a Young diagram. Standardness
of a tableau is exactly strict increase along these comparisons. -/
def YoungCellRowColumnLt {n : Nat} {lam : YoungDiagram n}
    (u v : YoungCell lam) : Prop :=
  (YoungCell.row u = YoungCell.row v ∧ YoungCell.col u < YoungCell.col v) ∨
    (YoungCell.col u = YoungCell.col v ∧ YoungCell.row u < YoungCell.row v)

/-- The boxes of a standard tableau, listed in increasing order of their
entries. -/
noncomputable def standardTableauBoxOrder {n : Nat} {lam : YoungDiagram n}
    (T : StandardYoungTableau lam) : List (YoungCell lam) :=
  List.ofFn (cellOfEntry T)

@[simp] theorem standardTableauBoxOrder_length
    {n : Nat} {lam : YoungDiagram n} (T : StandardYoungTableau lam) :
    (standardTableauBoxOrder T).length = n := by
  simp [standardTableauBoxOrder]

theorem cellOfEntry_injective {n : Nat} {lam : YoungDiagram n}
    (T : StandardYoungTableau lam) : Function.Injective (cellOfEntry T) := by
  intro a b hab
  have hentry := congrArg T.entry hab
  simpa only [entry_cellOfEntry] using hentry

theorem standardTableauBoxOrder_nodup
    {n : Nat} {lam : YoungDiagram n} (T : StandardYoungTableau lam) :
    (standardTableauBoxOrder T).Nodup := by
  rw [standardTableauBoxOrder, List.nodup_ofFn]
  exact cellOfEntry_injective T

/-- The box-order list of a standard tableau is a linear extension of the
strict row-or-column order. -/
theorem standardTableauBoxOrder_isLinearExtension
    {n : Nat} {lam : YoungDiagram n} (T : StandardYoungTableau lam) :
    IsLinearExtension YoungCellRowColumnLt (standardTableauBoxOrder T) := by
  refine ⟨standardTableauBoxOrder_nodup T, ?_⟩
  rw [List.pairwise_iff_getElem]
  intro i j hi hj hij
  simp only [standardTableauBoxOrder_length] at hi hj
  simp only [standardTableauBoxOrder, List.getElem_ofFn]
  intro hrel
  rcases hrel with hrow | hcol
  · have hlt := T.row_strict hrow.1 hrow.2
    rw [entry_cellOfEntry, entry_cellOfEntry] at hlt
    have hji : j < i := by simpa using hlt
    omega
  · have hlt := T.col_strict hcol.1 hcol.2
    rw [entry_cellOfEntry, entry_cellOfEntry] at hlt
    have hji : j < i := by simpa using hlt
    omega

/-- Every box occurs in the box-order list. -/
theorem mem_standardTableauBoxOrder
    {n : Nat} {lam : YoungDiagram n} (T : StandardYoungTableau lam)
    (u : YoungCell lam) :
    u ∈ standardTableauBoxOrder T := by
  rw [standardTableauBoxOrder, List.mem_ofFn']
  refine ⟨T.entry u, ?_⟩
  exact cellOfEntry_eq_of_entry T rfl

/-- Box-order lists of two tableaux of the same shape list the same boxes with
multiplicity one. -/
theorem standardTableauBoxOrder_perm
    {n : Nat} {lam : YoungDiagram n} (T U : StandardYoungTableau lam) :
    (standardTableauBoxOrder T).Perm (standardTableauBoxOrder U) := by
  apply (List.perm_ext_iff_of_nodup
    (standardTableauBoxOrder_nodup T)
    (standardTableauBoxOrder_nodup U)).2
  intro u
  simp only [mem_standardTableauBoxOrder]

/-- A tableau is determined by its increasing box-order list. -/
theorem standardTableauBoxOrder_injective
    {n : Nat} {lam : YoungDiagram n} {T U : StandardYoungTableau lam}
    (horder : standardTableauBoxOrder T = standardTableauBoxOrder U) :
    T = U := by
  have hcells : cellOfEntry T = cellOfEntry U := by
    exact List.ofFn_injective horder
  apply standardYoungTableau_ext_entry
  intro u
  let a := T.entry u
  have hcell : cellOfEntry T a = cellOfEntry U a := congrFun hcells a
  have hleft : cellOfEntry T a = u := cellOfEntry_eq_of_entry T rfl
  have hright : U.entry (cellOfEntry U a) = a := entry_cellOfEntry U a
  rw [hleft] at hcell
  have hu : U.entry u = a := by
    calc
      U.entry u = U.entry (cellOfEntry U a) := congrArg U.entry hcell
      _ = a := hright
  exact hu.symm

/-- Incomparable consecutive entry-cells cannot lie in one row. -/
theorem not_adjacentSameRow_of_incomparable
    {n : Nat} {lam : YoungDiagram (n + 1)}
    (T : StandardYoungTableau lam) (a : Fin n)
    (hinc : Incomparable YoungCellRowColumnLt
      (adjacentLoCell T a) (adjacentHiCell T a)) :
    ¬ adjacentSameRow T a := by
  intro hrow
  have hcol_ne :
      YoungCell.col (adjacentLoCell T a) ≠
        YoungCell.col (adjacentHiCell T a) := by
    intro hcol
    apply adjacentLoCell_ne_hiCell T a
    apply Subtype.ext
    apply Prod.ext
    · exact Fin.ext hrow
    · exact Fin.ext hcol
  rcases lt_or_gt_of_ne hcol_ne with hlt | hgt
  · exact hinc.1 (Or.inl ⟨hrow, hlt⟩)
  · exact hinc.2 (Or.inl ⟨hrow.symm, hgt⟩)

/-- Incomparable consecutive entry-cells cannot lie in one column. -/
theorem not_adjacentSameCol_of_incomparable
    {n : Nat} {lam : YoungDiagram (n + 1)}
    (T : StandardYoungTableau lam) (a : Fin n)
    (hinc : Incomparable YoungCellRowColumnLt
      (adjacentLoCell T a) (adjacentHiCell T a)) :
    ¬ adjacentSameCol T a := by
  intro hcol
  have hrow_ne :
      YoungCell.row (adjacentLoCell T a) ≠
        YoungCell.row (adjacentHiCell T a) := by
    intro hrow
    apply adjacentLoCell_ne_hiCell T a
    apply Subtype.ext
    apply Prod.ext
    · exact Fin.ext hrow
    · exact Fin.ext hcol
  rcases lt_or_gt_of_ne hrow_ne with hlt | hgt
  · exact hinc.1 (Or.inr ⟨hcol, hlt⟩)
  · exact hinc.2 (Or.inr ⟨hcol.symm, hgt⟩)

/-- Swapping adjacent tableau entries swaps exactly the corresponding two
positions in the box-order list. -/
theorem standardTableauBoxOrder_adjacentSwap
    {n : Nat} {lam : YoungDiagram (n + 1)}
    (T : StandardYoungTableau lam) (a : Fin n)
    (hrow : YoungCell.row (adjacentLoCell T a) ≠
      YoungCell.row (adjacentHiCell T a))
    (hcol : YoungCell.col (adjacentLoCell T a) ≠
      YoungCell.col (adjacentHiCell T a)) :
    standardTableauBoxOrder (adjacentSwapTableau T a hrow hcol) =
      ((standardTableauBoxOrder T).set (a : Nat) (adjacentHiCell T a)).set
        ((a : Nat) + 1) (adjacentLoCell T a) := by
  apply List.ext_getElem
  · simp
  · intro i hi_left hi_right
    have hi : i < n + 1 := by
      simpa [standardTableauBoxOrder] using hi_left
    let b : Fin (n + 1) := ⟨i, hi⟩
    by_cases hb_lo : b = adjacentEntryLo a
    · have hi_lo : i = (a : Nat) := congrArg Fin.val hb_lo
      subst i
      simp only [standardTableauBoxOrder, List.getElem_ofFn]
      change cellOfEntry (adjacentSwapTableau T a hrow hcol)
        (adjacentEntryLo a) = _
      rw [adjacentSwapTableau_cell_lo]
      rw [List.getElem_set_of_ne (by omega)]
      simp
    · by_cases hb_hi : b = adjacentEntryHi a
      · have hi_hi : i = (a : Nat) + 1 := by
          simpa [b, adjacentEntryHi] using congrArg Fin.val hb_hi
        subst i
        simp only [standardTableauBoxOrder, List.getElem_ofFn]
        change cellOfEntry (adjacentSwapTableau T a hrow hcol)
          (adjacentEntryHi a) = _
        rw [adjacentSwapTableau_cell_hi]
        simp
      · simp only [standardTableauBoxOrder, List.getElem_ofFn]
        rw [adjacentSwapTableau_cell_of_ne_lo_hi T a hrow hcol hb_lo hb_hi]
        have hi_ne_lo : i ≠ (a : Nat) := by
          intro h
          apply hb_lo
          apply Fin.ext
          simpa [b, adjacentEntryLo] using h
        have hi_ne_hi : i ≠ (a : Nat) + 1 := by
          intro h
          apply hb_hi
          apply Fin.ext
          simpa [b, adjacentEntryHi] using h
        rw [List.getElem_set_of_ne hi_ne_hi.symm,
          List.getElem_set_of_ne hi_ne_lo.symm]
        rw [List.getElem_ofFn]

/-- One edge in the standard-tableau adjacent-swap graph of a fixed shape. -/
def StandardTableauxAdjacent {n : Nat} {lam : YoungDiagram (n + 1)}
    (T U : StandardYoungTableau lam) : Prop :=
  ∃ (a : Fin n) (hrow : ¬ adjacentSameRow T a)
    (hcol : ¬ adjacentSameCol T a),
    U = adjacentSwapTableau T a hrow hcol

/-- One adjacent incomparable swap of a tableau's box-order list is induced by
one valid adjacent swap of tableau entries. -/
theorem standardTableauxAdjacent_of_boxOrder_adjacentSwap
    {n : Nat} {lam : YoungDiagram (n + 1)}
    (T : StandardYoungTableau lam) {ys : List (YoungCell lam)}
    (hstep : AdjacentIncomparableSwap YoungCellRowColumnLt
      (standardTableauBoxOrder T) ys) :
    ∃ U : StandardYoungTableau lam,
      StandardTableauxAdjacent T U ∧ standardTableauBoxOrder U = ys := by
  rcases hstep with ⟨pre, post, u, v, hinc, hsource, rfl⟩
  have hlength := congrArg List.length hsource
  simp only [standardTableauBoxOrder_length, List.length_append,
    List.length_cons] at hlength
  have hk : pre.length < n := by omega
  have hk_parent : pre.length < n + 1 := by omega
  have hk_succ_parent : pre.length + 1 < n + 1 := by omega
  let a : Fin n := ⟨pre.length, hk⟩
  have hu_get_opt : (standardTableauBoxOrder T)[pre.length]? = some u := by
    rw [hsource]
    simp
  have hv_get_opt :
      (standardTableauBoxOrder T)[pre.length + 1]? = some v := by
    rw [hsource]
    simp
  have hu_get : cellOfEntry T ⟨pre.length, hk_parent⟩ = u := by
    rw [List.getElem?_eq_getElem (by
      simpa [standardTableauBoxOrder] using hk_parent)] at hu_get_opt
    have hu_list := Option.some.inj hu_get_opt
    simpa only [standardTableauBoxOrder, List.getElem_ofFn] using hu_list
  have hv_get : cellOfEntry T ⟨pre.length + 1, hk_succ_parent⟩ = v := by
    rw [List.getElem?_eq_getElem (by
      simpa [standardTableauBoxOrder] using hk_succ_parent)] at hv_get_opt
    have hv_list := Option.some.inj hv_get_opt
    simpa only [standardTableauBoxOrder, List.getElem_ofFn] using hv_list
  have hu : adjacentLoCell T a = u := by
    simpa [adjacentLoCell, adjacentEntryLo, a] using hu_get
  have hv : adjacentHiCell T a = v := by
    simpa [adjacentHiCell, adjacentEntryHi, a] using hv_get
  have hinc' : Incomparable YoungCellRowColumnLt
      (adjacentLoCell T a) (adjacentHiCell T a) := by
    simpa [hu, hv] using hinc
  have hrow : ¬ adjacentSameRow T a :=
    not_adjacentSameRow_of_incomparable T a hinc'
  have hcol : ¬ adjacentSameCol T a :=
    not_adjacentSameCol_of_incomparable T a hinc'
  let U := adjacentSwapTableau T a hrow hcol
  refine ⟨U, ⟨a, hrow, hcol, rfl⟩, ?_⟩
  dsimp [U]
  rw [standardTableauBoxOrder_adjacentSwap]
  rw [hsource]
  simp [a, hu, hv]

/-- A finite path of adjacent incomparable box-order swaps lifts to a finite
path of valid adjacent tableau swaps. -/
theorem standardTableauxPath_of_boxOrderPath
    {n : Nat} {lam : YoungDiagram (n + 1)}
    (T : StandardYoungTableau lam) {ys : List (YoungCell lam)}
    (hreach : LinearExtensionSwapReachable YoungCellRowColumnLt
      (standardTableauBoxOrder T) ys) :
    ∃ U : StandardYoungTableau lam,
      Relation.ReflTransGen (StandardTableauxAdjacent (lam := lam)) T U ∧
        standardTableauBoxOrder U = ys := by
  induction hreach with
  | refl =>
      exact ⟨T, Relation.ReflTransGen.refl, rfl⟩
  | tail hxy hyz ih =>
      rcases ih with ⟨U, hTU, hUorder⟩
      rw [← hUorder] at hyz
      rcases standardTableauxAdjacent_of_boxOrder_adjacentSwap U hyz with
        ⟨V, hUV, hVorder⟩
      exact ⟨V, hTU.tail hUV, hVorder⟩

/-- Lemma 5.3 connectedness statement: any two standard tableaux of the same
shape are connected by adjacent swaps that remain standard. -/
def StandardTableauxSwapConnectedStatement : Prop :=
  ∀ {n : Nat} (lam : YoungDiagram (n + 1))
    (T U : StandardYoungTableau lam),
    Relation.ReflTransGen (StandardTableauxAdjacent (lam := lam)) T U

/-- The adjacent-swap graph of standard tableaux of every fixed
Young shape is connected. -/
theorem standardTableauxSwapConnected :
    StandardTableauxSwapConnectedStatement := by
  intro n lam T U
  have hreach : LinearExtensionSwapReachable YoungCellRowColumnLt
      (standardTableauBoxOrder T) (standardTableauBoxOrder U) :=
    linearExtensions_connected_by_adjacent_incomparable_swaps
      YoungCellRowColumnLt
      (standardTableauBoxOrder T) (standardTableauBoxOrder U)
      (standardTableauBoxOrder_isLinearExtension T)
      (standardTableauBoxOrder_isLinearExtension U)
      (standardTableauBoxOrder_perm T U)
  rcases standardTableauxPath_of_boxOrderPath T hreach with
    ⟨V, hTV, hVorder⟩
  have hVU : V = U := standardTableauBoxOrder_injective hVorder
  subst V
  exact hTV

/-- Paper Lemma 5.3: standard tableaux of a fixed shape are connected by valid
adjacent swaps. -/
theorem S05_Lem5_03_standardTableauxSwapConnectedness :
    StandardTableauxSwapConnectedStatement :=
  standardTableauxSwapConnected

end DictatorshipTesting
