import Mathlib

/-!
# Connectivity of finite linear extensions

Any two list models of a finite linear extension with the same entries are
connected by adjacent swaps of incomparable elements.
-/

namespace AlgebraicLibrary

variable {α : Type*}

/-- Two elements are incomparable for a strict order-like relation `lt`. -/
def Incomparable (lt : α → α → Prop) (a b : α) : Prop :=
  ¬ lt a b ∧ ¬ lt b a

/-- A duplicate-free list model for a linear extension. -/
def IsLinearExtension (lt : α → α → Prop) (xs : List α) : Prop :=
  xs.Nodup ∧ xs.Pairwise (fun a b => ¬ lt b a)

/-- One adjacent swap of incomparable neighboring entries. -/
def AdjacentIncomparableSwap (lt : α → α → Prop)
    (xs ys : List α) : Prop :=
  ∃ pre post a b,
    Incomparable lt a b ∧
      xs = pre ++ a :: b :: post ∧
      ys = pre ++ b :: a :: post

/-- Reachability generated by adjacent incomparable swaps. -/
def LinearExtensionSwapReachable (lt : α → α → Prop)
    (xs ys : List α) : Prop :=
  Relation.ReflTransGen (AdjacentIncomparableSwap lt) xs ys

theorem adjacentIncomparableSwap_symm {lt : α → α → Prop} {xs ys : List α}
    (h : AdjacentIncomparableSwap lt xs ys) :
    AdjacentIncomparableSwap lt ys xs := by
  rcases h with ⟨pre, post, a, b, hinc, rfl, rfl⟩
  exact ⟨pre, post, b, a, ⟨hinc.2, hinc.1⟩, rfl, rfl⟩

theorem nodup_adjacent_swap {pre post : List α} {a b : α}
    (h : (pre ++ a :: b :: post).Nodup) :
    (pre ++ b :: a :: post).Nodup := by
  have hp : (pre ++ b :: a :: post).Perm (pre ++ a :: b :: post) :=
    List.Perm.append_left _ (List.Perm.swap _ _ _)
  exact hp.nodup_iff.mpr h

/-- Swapping adjacent incomparable entries preserves linear-extension status. -/
theorem isLinearExtension_adjacent_swap {lt : α → α → Prop}
    {pre post : List α} {a b : α}
    (hlin : IsLinearExtension lt (pre ++ a :: b :: post))
    (hinc : Incomparable lt a b) :
    IsLinearExtension lt (pre ++ b :: a :: post) := by
  classical
  rcases hlin with ⟨hnodup, hpair⟩
  refine ⟨nodup_adjacent_swap hnodup, ?_⟩
  let R : α → α → Prop := fun x y => ¬ lt y x
  change (pre ++ b :: a :: post).Pairwise R
  change (pre ++ a :: b :: post).Pairwise R at hpair
  rw [List.pairwise_append] at hpair ⊢
  rcases hpair with ⟨hpre, htail, hcross⟩
  rw [List.pairwise_cons] at htail
  rcases htail with ⟨ha_all, hbtail⟩
  rw [List.pairwise_cons] at hbtail
  rcases hbtail with ⟨hb_post, hpost⟩
  refine ⟨hpre, ?_, ?_⟩
  · rw [List.pairwise_cons]
    refine ⟨?_, ?_⟩
    · intro y hy
      rcases List.mem_cons.mp hy with rfl | hy
      · simpa [R] using hinc.1
      · exact hb_post y hy
    · rw [List.pairwise_cons]
      refine ⟨?_, hpost⟩
      intro y hy
      exact ha_all y (by simp [hy])
  intro x hx y hy
  have hy' : y ∈ a :: b :: post := by
    simp only [List.mem_cons] at hy ⊢
    tauto
  exact hcross x hx y hy'

theorem isLinearExtension_of_adjacentIncomparableSwap
    {lt : α → α → Prop} {xs ys : List α}
    (hstep : AdjacentIncomparableSwap lt xs ys)
    (hlin : IsLinearExtension lt xs) :
    IsLinearExtension lt ys := by
  rcases hstep with ⟨pre, post, a, b, hinc, rfl, rfl⟩
  exact isLinearExtension_adjacent_swap hlin hinc

theorem adjacentIncomparableSwap_cons {lt : α → α → Prop}
    (c : α) {xs ys : List α}
    (hstep : AdjacentIncomparableSwap lt xs ys) :
    AdjacentIncomparableSwap lt (c :: xs) (c :: ys) := by
  rcases hstep with ⟨pre, post, a, b, hinc, rfl, rfl⟩
  exact ⟨c :: pre, post, a, b, hinc, by simp, by simp⟩

theorem reflTransGen_adjacentIncomparableSwap_cons
    {lt : α → α → Prop} (c : α) {xs ys : List α}
    (hreach : LinearExtensionSwapReachable lt xs ys) :
    LinearExtensionSwapReachable lt (c :: xs) (c :: ys) := by
  induction hreach with
  | refl => exact Relation.ReflTransGen.refl
  | tail hxy hyz ih =>
      exact ih.tail (adjacentIncomparableSwap_cons c hyz)

theorem isLinearExtension_of_swapReachable {lt : α → α → Prop}
    {xs ys : List α}
    (hreach : LinearExtensionSwapReachable lt xs ys)
    (hlin : IsLinearExtension lt xs) :
    IsLinearExtension lt ys := by
  induction hreach with
  | refl => exact hlin
  | tail hxy hyz ih =>
      exact isLinearExtension_of_adjacentIncomparableSwap hyz ih

theorem perm_of_adjacentIncomparableSwap {lt : α → α → Prop}
    {xs ys : List α} (hstep : AdjacentIncomparableSwap lt xs ys) :
    xs.Perm ys := by
  rcases hstep with ⟨pre, post, a, b, _hinc, rfl, rfl⟩
  exact List.Perm.append_left pre (List.Perm.swap b a post)

theorem perm_of_swapReachable {lt : α → α → Prop}
    {xs ys : List α} (hreach : LinearExtensionSwapReachable lt xs ys) :
    xs.Perm ys := by
  induction hreach with
  | refl => exact List.Perm.refl _
  | tail hxy hyz ih =>
      exact ih.trans (perm_of_adjacentIncomparableSwap hyz)

/-- Every entry crossed when moving the target's head to the front of the
source is incomparable with that head. -/
theorem linearExtension_crossed_elements_incomparable
    [DecidableEq α] {lt : α → α → Prop}
    {pre post bs : List α} {b : α}
    (hsource : IsLinearExtension lt (pre ++ b :: post))
    (htarget : IsLinearExtension lt (b :: bs))
    (hperm : (pre ++ b :: post).Perm (b :: bs)) :
    ∀ a ∈ pre, Incomparable lt a b := by
  intro a ha
  have hsourcePair := hsource.2
  rw [List.pairwise_append] at hsourcePair
  rcases hsourcePair with ⟨_hpre, _htail, hcross⟩
  have hnot_ba : ¬ lt b a := hcross a ha b (by simp)
  have hab_ne : a ≠ b := by
    exact (List.nodup_append.mp hsource.1).2.2 a ha b (by simp)
  have ha_source : a ∈ pre ++ b :: post := List.mem_append_left _ ha
  have ha_target : a ∈ b :: bs := hperm.mem_iff.mp ha_source
  have ha_bs : a ∈ bs :=
    (List.mem_cons.mp ha_target).resolve_left hab_ne
  have htargetPair := htarget.2
  rw [List.pairwise_cons] at htargetPair
  have hnot_ab : ¬ lt a b := htargetPair.1 a ha_bs
  exact ⟨hnot_ab, hnot_ba⟩

/-- Repeated adjacent swaps move `b` across an incomparable prefix. -/
theorem reflTransGen_adjacentIncomparableSwap_move_left
    {lt : α → α → Prop} (pre post : List α) (b : α)
    (hinc : ∀ a ∈ pre, Incomparable lt a b) :
    LinearExtensionSwapReachable lt
      (pre ++ b :: post) (b :: pre ++ post) := by
  induction pre with
  | nil => exact Relation.ReflTransGen.refl
  | cons a pre ih =>
      have hinc_a : Incomparable lt a b := hinc a (by simp)
      have hinc_pre : ∀ c ∈ pre, Incomparable lt c b := by
        intro c hc
        exact hinc c (by simp [hc])
      have htail := ih hinc_pre
      have hlift := reflTransGen_adjacentIncomparableSwap_cons a htail
      have hstep : AdjacentIncomparableSwap lt
          (a :: b :: pre ++ post) (b :: a :: pre ++ post) := by
        exact ⟨[], pre ++ post, a, b, hinc_a, by simp, by simp⟩
      exact hlift.tail hstep

/-- Any two finite list-level linear extensions with the same entries are
connected by adjacent swaps of incomparable neighboring elements. -/
theorem linearExtensions_connected_by_adjacent_incomparable_swaps
    [DecidableEq α] (lt : α → α → Prop) (xs ys : List α)
    (hxs : IsLinearExtension lt xs)
    (hys : IsLinearExtension lt ys)
    (hperm : xs.Perm ys) :
    LinearExtensionSwapReachable lt xs ys := by
  induction ys generalizing xs with
  | nil =>
      have hnil : xs = [] := hperm.eq_nil
      subst xs
      exact Relation.ReflTransGen.refl
  | cons b bs ih =>
      have hb_source : b ∈ xs := hperm.mem_iff.mpr (by simp)
      rcases List.append_of_mem hb_source with ⟨pre, post, rfl⟩
      have hinc : ∀ a ∈ pre, Incomparable lt a b :=
        linearExtension_crossed_elements_incomparable hxs hys hperm
      have hmove : LinearExtensionSwapReachable lt
          (pre ++ b :: post) (b :: pre ++ post) :=
        reflTransGen_adjacentIncomparableSwap_move_left pre post b hinc
      have hmovedLin : IsLinearExtension lt (b :: pre ++ post) :=
        isLinearExtension_of_swapReachable hmove hxs
      have hmovedPerm : (pre ++ b :: post).Perm (b :: pre ++ post) :=
        perm_of_swapReachable hmove
      have hconsPerm : (b :: pre ++ post).Perm (b :: bs) :=
        hmovedPerm.symm.trans hperm
      have htailPerm : (pre ++ post).Perm bs := hconsPerm.cons_inv
      have hsourceTail : IsLinearExtension lt (pre ++ post) :=
        ⟨hmovedLin.1.of_cons, hmovedLin.2.of_cons⟩
      have htargetTail : IsLinearExtension lt bs :=
        ⟨hys.1.of_cons, hys.2.of_cons⟩
      have htailReach : LinearExtensionSwapReachable lt (pre ++ post) bs :=
        ih (pre ++ post) hsourceTail htargetTail htailPerm
      exact hmove.trans
        (reflTransGen_adjacentIncomparableSwap_cons b htailReach)

end AlgebraicLibrary
